name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run tests
        run: |
          go test -v ./...

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-linux-amd64.tar.gz | tar -xzv
          sudo mv golangci-lint-1.50.1-linux-amd64/golangci-lint /usr/local/bin/

      - name: Run linters
        run: |
          golangci-lint run

      - name: Build the Go project
        run: |
          go build -v